### ISSUE TITLE
Navigation to prev/next todo-comment (from upstream)

### ISSUE THREAD

**Issue by axieax** [B4mbus/todo-comments.nvim#2]
https://github.com/folke/todo-comments.nvim/issues/77 :))

**Comment by B4mbus** [comment]
Hey. First of all I'm incredibely confused. I have been getting NO notifications regarding this fork, now I see there are four issues.. Folke is now active on github and the original repo is maintained so I'm going to issue a deprecation notice and delete this fork in a week.
