### ISSUE TITLE
Is this version going to be getting all new updates from the upstream ?

### ISSUE THREAD

**Issue by Sanix-Darker** [B4mbus/todo-comments.nvim#3]
I kind of understand the reason for this fork... just like [i3gaps](https://github.com/Airblader/i3) is for [i3](https://github.com/i3/i3) but are you going to get updates from the upstream frequently ?

**Comment by B4mbus** [comment]
Hey. First of all I'm incredibely confused. I have been getting NO notifications regarding this fork, now I see there are four issues.. Folke is now active on github and the original repo is maintained so I'm going to issue a deprecation notice and delete this fork in a week.
