### ISSUE TITLE
support for single letter labels

### ISSUE THREAD

**Issue by JoseConseco** [B4mbus/todo-comments.nvim#4]
using # ?: - for NOTE
or   # !: as warning wont work in todo-comments.
Any chance we could get support for ?,! as  alt  labels option for comments?

**Comment by B4mbus** [comment]
Hey. First of all I'm incredibely confused. I have been getting NO notifications regarding this fork, now I see there are four issues.. Folke is now active on github and the original repo is maintained so I'm going to issue a deprecation notice and delete this fork in a week.

That being said - all issues and PRs should now be posted on the original repository, sorry.
