### ISSUE TITLE
Bug fix from upstream

### ISSUE THREAD

**Issue by axieax** [B4mbus/todo-comments.nvim#5]
https://github.com/folke/todo-comments.nvim/pull/120

**Comment by B4mbus** [comment]
Hey. First of all I'm incredibely confused. I have been getting NO notifications regarding this fork, now I see there are four issues.. Folke is now active on github and the original repo is maintained so I'm going to issue a deprecation notice and delete this fork in a week.

That being said - all issues and PRs should now be posted on the original repository, sorry.

Regarding this bug fix - iirc folke fixed this already.
